# Specify location of manifest files for each package manager

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "gitsubmodule"